#! /bin/sh

export DISABLE_HIST=false

sxhkd &
/usr/lib/geoclue-2.0/demos/agent &
~/.fehbg
picom & 
~/.config/polybar/launch.sh
killall -q dunst
/usr/bin/dunst &
killall -q redshift
# redshift doesn't get terminated directly after invoking the kill command
# we have to wait until it's done transitioning before launching redshift again:
tail --pid=$(pidof redshift) -f /dev/null
redshift -l geoclue2 &

if [[ $(autorandr --detected) = "desk" ]]; then
  #bspc monitor eDP-1 -d 6 7 8 9 10
  #bspc monitor HDMI-2 -d 1 2 3 4 5
  bspc monitor HDMI-2 -d I II III IV V VI VII VIII IX X
else
  bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
fi


bspc config border_width         1
bspc config window_gap           10

#bspc config focused_border_color \#de4949
#bspc config normal_border_color \#ba6868
#bspc config active_border_color \#ba6868
#bspc config presel_feedback_color \#2f2f2f

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

xsetroot -cursor_name left_ptr
